// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID           pgtype.UUID
	Email        string
	PasswordHash string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type AuditEvent struct {
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
	ActorAccountID pgtype.UUID
	Action         string
	TargetType     string
	TargetID       pgtype.UUID
	Metadata       []byte
	CreatedAt      pgtype.Timestamptz
}

type Organization struct {
	ID        pgtype.UUID
	Name      string
	Slug      string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type OrganizationMembership struct {
	OrganizationID pgtype.UUID
	AccountID      pgtype.UUID
	Email          string
	Role           string
	CreatedAt      pgtype.Timestamptz
}

type Project struct {
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
	Name           string
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type Session struct {
	ID        pgtype.UUID
	AccountID pgtype.UUID
	TokenHash []byte
	ExpiresAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}
