// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: organizations.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listAccountOrganizations = `-- name: ListAccountOrganizations :many
SELECT o.id, o.name, o.slug, o.created_at
FROM organizations AS o
JOIN organization_memberships AS m ON m.organization_id = o.id
WHERE m.account_id = $1
  AND ($2::text = '' OR o.id::text > $2::text)
ORDER BY o.id
LIMIT $3
`

type ListAccountOrganizationsParams struct {
	AccountID pgtype.UUID
	Column2   string
	Limit     int32
}

type ListAccountOrganizationsRow struct {
	ID        pgtype.UUID
	Name      string
	Slug      string
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) ListAccountOrganizations(ctx context.Context, arg ListAccountOrganizationsParams) ([]ListAccountOrganizationsRow, error) {
	rows, err := q.db.Query(ctx, listAccountOrganizations, arg.AccountID, arg.Column2, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAccountOrganizationsRow
	for rows.Next() {
		var i ListAccountOrganizationsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrganizationMemberships = `-- name: ListOrganizationMemberships :many
SELECT m.organization_id, m.account_id, a.email, m.role, m.created_at
FROM organization_memberships AS m
JOIN accounts AS a ON a.id = m.account_id
WHERE m.organization_id = $1
  AND ($2::text = '' OR m.account_id::text > $2::text)
ORDER BY m.account_id
LIMIT $3
`

type ListOrganizationMembershipsParams struct {
	OrganizationID pgtype.UUID
	Column2        string
	Limit          int32
}

func (q *Queries) ListOrganizationMemberships(ctx context.Context, arg ListOrganizationMembershipsParams) ([]OrganizationMembership, error) {
	rows, err := q.db.Query(ctx, listOrganizationMemberships, arg.OrganizationID, arg.Column2, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrganizationMembership
	for rows.Next() {
		var i OrganizationMembership
		if err := rows.Scan(
			&i.OrganizationID,
			&i.AccountID,
			&i.Email,
			&i.Role,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
