/**
 * Stable TanStack Query key factories for the Console.
 *
 * Keeping keys here makes invalidation discoverable and prevents two routes
 * from accidentally treating the same server resource as different state.
 * Prefix keys intentionally omit the final resource identifier so they can
 * invalidate a whole project collection when a mutation changes it.
 */
export const queryKeys = {
  account: () => ["account"] as const,
  accountSessions: () => ["account-sessions"] as const,
  organizations: () => ["organizations"] as const,
  projects: (organizationID?: string) => organizationID ? ["projects", organizationID] as const : ["projects"] as const,
  project: (projectID: string) => ["project", projectID] as const,
  projectUsage: (projectID: string) => ["project-usage", projectID] as const,
  projectUsageMetering: (projectID: string, from: string, to: string) => ["project-usage-metering", projectID, from, to] as const,
  projectResource: (projectID: string, resource: string) => ["project-resource", projectID, resource] as const,
  projectAuditEvents: (projectID: string) => ["project-audit-events", projectID] as const,
  projectTraces: (projectID: string) => ["project-traces", projectID] as const,
  projectServiceLayout: (projectID: string) => ["service-layout", projectID] as const,
  serviceFunctions: (projectID: string) => ["service-functions", projectID] as const,
  serviceSites: (projectID: string) => ["service-sites", projectID] as const,
  serviceDatabases: (projectID: string) => ["service-databases", projectID] as const,
  serviceBuckets: (projectID: string) => ["service-buckets", projectID] as const,
  projectAuthSettings: (projectID: string) => ["project-auth-settings", projectID] as const,
  projectUsers: (projectID: string) => ["project-users", projectID] as const,
  projectAPIKeys: (projectID: string) => ["project-api-keys", projectID] as const,
  projectWebhooks: (projectID: string) => ["project-webhooks", projectID] as const,
  projectWebhookDeliveries: (projectID: string, webhookID: string) => ["project-webhook-deliveries", projectID, webhookID] as const,
  projectDatabases: (projectID: string) => ["project-databases", projectID] as const,
  databaseTables: (projectID: string, databaseID: string) => ["database-tables", projectID, databaseID] as const,
  databaseColumns: (projectID: string, databaseID: string, tableID: string) => ["database-columns", projectID, databaseID, tableID] as const,
  databaseIndexes: (projectID: string, databaseID: string, tableID: string) => ["database-indexes", projectID, databaseID, tableID] as const,
  databaseRows: (projectID: string, databaseID: string, tableID: string, search = "", searchColumn = "") => search || searchColumn ? ["database-rows", projectID, databaseID, tableID, searchColumn, search] as const : ["database-rows", projectID, databaseID, tableID] as const,
  projectStorageBuckets: (projectID: string) => ["project-storage-buckets", projectID] as const,
  storageFiles: (projectID: string, bucketID: string) => ["storage-files", projectID, bucketID] as const,
  projectFunctions: (projectID: string) => ["project-functions", projectID] as const,
  functionDeployments: (projectID: string, functionID: string) => ["function-deployments", projectID, functionID] as const,
  functionBuildLogs: (projectID: string, functionID: string, deploymentID: string) => ["function-build-logs", projectID, functionID, deploymentID] as const,
  functionVariables: (projectID: string, functionID: string) => ["function-variables", projectID, functionID] as const,
  functionExecutions: (projectID: string, functionID: string) => ["function-executions", projectID, functionID] as const,
  functionExecutionLogs: (projectID: string, functionID: string, executionID: string) => ["function-execution-logs", projectID, functionID, executionID] as const,
  projectSites: (projectID: string) => ["project-sites", projectID] as const,
  siteDeployments: (projectID: string, siteID: string) => ["site-deployments", projectID, siteID] as const,
  siteBuildLogs: (projectID: string, siteID: string, deploymentID: string) => ["site-build-logs", projectID, siteID, deploymentID] as const,
  siteDomains: (projectID: string, siteID: string) => ["site-domains", projectID, siteID] as const,
  deployments: (projectID: string) => ["deployments", projectID] as const,
  deployment: (projectID: string, resourceType: string, resourceID: string) => ["deployments", projectID, resourceType, resourceID] as const,
  messagingProviders: (projectID: string) => ["messaging-providers", projectID] as const,
  messagingTopics: (projectID: string) => ["messaging-topics", projectID] as const,
  messagingMessages: (projectID: string) => ["messaging-messages", projectID] as const,
  messagingDeliveries: (projectID: string, messageID?: string | null) => messageID ? ["messaging-deliveries", projectID, messageID] as const : ["messaging-deliveries", projectID] as const,
  agents: () => ["agents"] as const,
  agentCatalog: () => ["agent-catalog"] as const,
  agent: (agentID: string) => ["agent", agentID] as const,
  agentRuns: (agentID: string) => ["agent-runs", agentID] as const,
  agentRunLogs: (agentID: string, runID?: string) => runID ? ["agent-run-logs", agentID, runID] as const : ["agent-run-logs", agentID] as const,
  health: () => ["healthz"] as const,
  readiness: () => ["readyz"] as const,
  organizationIncidents: (organizationID: string) => ["admin-incidents", organizationID] as const,
  organizationTraces: (organizationID: string) => ["admin-traces", organizationID] as const,
  organizationMemberships: (organizationID: string) => ["admin-memberships", organizationID] as const,
  organizationInvitations: (organizationID: string) => ["admin-invitations", organizationID] as const,
  organizationAuditEvents: (organizationID?: string) => organizationID ? ["admin-settings-audit", organizationID] as const : ["admin-settings-audit"] as const,
  adminProjects: (organizationID: string) => ["admin-projects", organizationID] as const,
  adminProjectUsage: (projectID: string) => ["admin-project-usage", projectID] as const,
  adminUsageProjects: (organizationID: string) => ["admin-usage-projects", organizationID] as const,
  adminUsageDetail: (projectID: string) => ["admin-usage-detail", projectID] as const,
  adminRuns: () => ["admin-runs-agents"] as const,
  adminAgentRuns: (agentID: string) => ["admin-runs", agentID] as const,
  adminWorkers: () => ["admin-workers-agents"] as const,
} as const;
