package httpapi

import "github.com/go-chi/chi/v5"

func (s *Server) registerDatabaseRoutes(r chi.Router) {
	r.With(s.requireProjectManagement).Get("/projects/{projectID}/databases", s.listProjectDatabases)
	r.With(s.requireProjectManagement).Post("/projects/{projectID}/databases", s.createProjectDatabase)
	r.With(s.requireProjectManagement).Get("/projects/{projectID}/databases/{databaseID}", s.getProjectDatabase)
	r.With(s.requireProjectManagement).Delete("/projects/{projectID}/databases/{databaseID}", s.deleteProjectDatabase)
	r.With(s.requireProjectManagement).Get("/projects/{projectID}/databases/{databaseID}/tables", s.listDatabaseTables)
	r.With(s.requireProjectManagement).Post("/projects/{projectID}/databases/{databaseID}/tables", s.createDatabaseTable)
	r.With(s.requireProjectManagement).Get("/projects/{projectID}/databases/{databaseID}/tables/{tableID}", s.getDatabaseTable)
	r.With(s.requireProjectManagement).Patch("/projects/{projectID}/databases/{databaseID}/tables/{tableID}", s.updateDatabaseTable)
	r.With(s.requireProjectManagement).Delete("/projects/{projectID}/databases/{databaseID}/tables/{tableID}", s.deleteDatabaseTable)
	r.With(s.requireProjectManagement).Get("/projects/{projectID}/databases/{databaseID}/tables/{tableID}/columns", s.listDatabaseColumns)
	r.With(s.requireProjectManagement).Post("/projects/{projectID}/databases/{databaseID}/tables/{tableID}/columns", s.createDatabaseColumn)
	r.With(s.requireProjectManagement).Delete("/projects/{projectID}/databases/{databaseID}/tables/{tableID}/columns/{columnID}", s.deleteDatabaseColumn)
	r.With(s.requireProjectManagement).Get("/projects/{projectID}/databases/{databaseID}/tables/{tableID}/indexes", s.listDatabaseIndexes)
	r.With(s.requireProjectManagement).Post("/projects/{projectID}/databases/{databaseID}/tables/{tableID}/indexes", s.createDatabaseIndex)
	r.With(s.requireProjectManagement).Delete("/projects/{projectID}/databases/{databaseID}/tables/{tableID}/indexes/{indexID}", s.deleteDatabaseIndex)
	r.With(s.requireProjectManagement).Get("/projects/{projectID}/databases/{databaseID}/relationships", s.listDatabaseRelationships)
	r.With(s.requireProjectManagement).Post("/projects/{projectID}/databases/{databaseID}/relationships", s.createDatabaseRelationship)
	r.With(s.requireProjectManagement).Get("/projects/{projectID}/databases/{databaseID}/relationships/{relationshipID}", s.getDatabaseRelationship)
	r.With(s.requireProjectManagement).Delete("/projects/{projectID}/databases/{databaseID}/relationships/{relationshipID}", s.deleteDatabaseRelationship)
	r.With(s.requireProjectManagement).Get("/projects/{projectID}/databases/{databaseID}/backups", s.listDatabaseBackups)
	r.With(s.requireProjectManagement).Post("/projects/{projectID}/databases/{databaseID}/backups", s.createDatabaseBackup)
	r.With(s.requireProjectManagement).Get("/projects/{projectID}/databases/{databaseID}/backups/{backupID}", s.getDatabaseBackup)
	r.With(s.requireProjectManagement).Get("/projects/{projectID}/databases/{databaseID}/backups/{backupID}/download", s.downloadDatabaseBackup)
	r.With(s.requireProjectManagement).Post("/projects/{projectID}/databases/{databaseID}/backups/{backupID}/restore", s.restoreDatabaseBackup)
	r.With(s.requireProjectManagement).Delete("/projects/{projectID}/databases/{databaseID}/backups/{backupID}", s.deleteDatabaseBackup)
	r.With(s.requireProjectDataActor).Get("/projects/{projectID}/databases/{databaseID}/tables/{tableID}/export", s.exportDatabaseRows)
	r.With(s.requireProjectDataActor).Get("/projects/{projectID}/databases/{databaseID}/tables/{tableID}/rows", s.listDatabaseRows)
	r.With(s.requireProjectDataActor).Post("/projects/{projectID}/databases/{databaseID}/tables/{tableID}/rows", s.createDatabaseRow)
	r.With(s.requireProjectDataActor).Post("/projects/{projectID}/databases/{databaseID}/tables/{tableID}/rows/import", s.importDatabaseRows)
	r.With(s.requireProjectDataActor).Post("/projects/{projectID}/databases/{databaseID}/tables/{tableID}/rows/transaction", s.transactDatabaseRows)
	r.With(s.requireProjectDataActor).Get("/projects/{projectID}/databases/{databaseID}/tables/{tableID}/rows/{rowID}", s.getDatabaseRow)
	r.With(s.requireProjectDataActor).Patch("/projects/{projectID}/databases/{databaseID}/tables/{tableID}/rows/{rowID}", s.updateDatabaseRow)
	r.With(s.requireProjectDataActor).Delete("/projects/{projectID}/databases/{databaseID}/tables/{tableID}/rows/{rowID}", s.deleteDatabaseRow)
}
