package httpapi

import (
	"errors"
	"fmt"
	"net/http"
	"strconv"
	"strings"
	"time"

	"github.com/google/uuid"
	"github.com/stealth-cloud/stealth/services/api/internal/domain"
	"github.com/stealth-cloud/stealth/services/api/internal/repository"
)

const (
	realtimePollInterval = 500 * time.Millisecond
	realtimeHeartbeat    = 15 * time.Second
	realtimeBatchSize    = 100
)

// realtime streams the project event outbox as Server-Sent Events. The
// transport deliberately reuses the permission-aware data actor middleware:
// Console sessions and realtime.read API keys can inspect the complete stream,
// while application sessions receive only row events they could read through
// the Database API. Anonymous callers are rejected by the repository.
func (s *Server) realtime(w http.ResponseWriter, r *http.Request) {
	projectID, ok := pathUUID(w, r, "projectID")
	if !ok {
		return
	}
	after, err := realtimeCursor(r)
	if err != nil {
		writeError(w, http.StatusUnprocessableEntity, "validation_error", err.Error())
		return
	}
	filter, err := realtimeEventFilter(r.URL.Query().Get("events"))
	if err != nil {
		writeError(w, http.StatusUnprocessableEntity, "validation_error", err.Error())
		return
	}
	if s.realtimeSlots != nil {
		select {
		case s.realtimeSlots <- struct{}{}:
			defer func() { <-s.realtimeSlots }()
		default:
			w.Header().Set("Retry-After", "1")
			writeError(w, http.StatusTooManyRequests, "rate_limited", "too many realtime streams are active")
			return
		}
	}

	// Authenticate and authorize before committing to a streaming response so
	// errors remain a normal JSON envelope. The first query also validates that
	// a project still exists for the supplied actor.
	if _, _, err := s.repo.ListRealtimeEvents(r.Context(), projectID, databaseActorFrom(r), after, 1); realtimeResourceError(w, err) {
		return
	}

	flusher, ok := w.(http.Flusher)
	if !ok {
		writeError(w, http.StatusInternalServerError, "internal_error", "streaming is not supported by this server")
		return
	}
	w.Header().Set("Content-Type", "text/event-stream; charset=utf-8")
	w.Header().Set("Cache-Control", "no-cache, no-transform")
	w.Header().Set("Connection", "keep-alive")
	w.Header().Set("X-Accel-Buffering", "no")
	w.WriteHeader(http.StatusOK)
	_, _ = fmt.Fprint(w, "retry: 3000\n\n")
	flusher.Flush()

	poll := time.NewTicker(realtimePollInterval)
	defer poll.Stop()
	heartbeat := time.NewTicker(realtimeHeartbeat)
	defer heartbeat.Stop()
	actor := databaseActorFrom(r)
	for {
		items, next, listErr := s.repo.ListRealtimeEvents(r.Context(), projectID, actor, after, realtimeBatchSize)
		if listErr != nil {
			// Once headers have been sent an SSE error cannot be represented as
			// JSON. Send a terminal event and close; clients can reconnect using
			// the last event id they received.
			_, _ = fmt.Fprintf(w, "event: error\ndata: %s\n\n", strconv.Quote("realtime stream unavailable"))
			flusher.Flush()
			return
		}
		if next != nil {
			after = next
		}
		for _, item := range items {
			if !filter.matches(item.EventName) {
				continue
			}
			if err := writeRealtimeEvent(w, flusher, item); err != nil {
				return
			}
		}
		if len(items) > 0 {
			// Drain any backlog without waiting for the next ticker tick.
			continue
		}
		select {
		case <-r.Context().Done():
			return
		case <-poll.C:
		case <-heartbeat.C:
			if _, err := fmt.Fprint(w, ": keep-alive\n\n"); err != nil {
				return
			}
			flusher.Flush()
		}
	}
}

func writeRealtimeEvent(w http.ResponseWriter, flusher http.Flusher, item domain.RealtimeEvent) error {
	if len(item.Payload) == 0 || strings.ContainsAny(item.EventName, "\r\n") {
		return errors.New("invalid realtime event")
	}
	if _, err := fmt.Fprintf(w, "id: %s\nevent: %s\n", item.ID, item.EventName); err != nil {
		return err
	}
	// JSON generated by the repository is compact, but split defensively so a
	// future payload formatter cannot inject a new SSE field through a raw
	// newline.
	for _, line := range strings.Split(string(item.Payload), "\n") {
		if _, err := fmt.Fprintf(w, "data: %s\n", line); err != nil {
			return err
		}
	}
	if _, err := fmt.Fprint(w, "\n"); err != nil {
		return err
	}
	flusher.Flush()
	return nil
}

func realtimeCursor(r *http.Request) (*uuid.UUID, error) {
	value := strings.TrimSpace(r.URL.Query().Get("cursor"))
	if value == "" {
		value = strings.TrimSpace(r.Header.Get("Last-Event-ID"))
	}
	if value == "" {
		return nil, nil
	}
	if len(value) > 64 {
		return nil, errors.New("cursor is too long")
	}
	id, err := uuid.Parse(value)
	if err != nil {
		return nil, errors.New("cursor must be a UUID")
	}
	return &id, nil
}

type realtimeFilter struct {
	all    bool
	events map[string]struct{}
}

func (f realtimeFilter) matches(event string) bool {
	if f.all {
		return true
	}
	_, ok := f.events[event]
	return ok
}

func realtimeEventFilter(raw string) (realtimeFilter, error) {
	if strings.TrimSpace(raw) == "" {
		return realtimeFilter{all: true}, nil
	}
	parts := strings.Split(raw, ",")
	normalized, err := repository.NormalizeWebhookEvents(parts)
	if err != nil {
		return realtimeFilter{}, errors.New("events must be comma-separated event names")
	}
	filter := realtimeFilter{events: make(map[string]struct{}, len(normalized))}
	for _, event := range normalized {
		if event == "*" {
			filter.all = true
			continue
		}
		filter.events[event] = struct{}{}
	}
	return filter, nil
}

func realtimeResourceError(w http.ResponseWriter, err error) bool {
	if err == nil {
		return false
	}
	switch {
	case errors.Is(err, repository.ErrRealtimeForbidden), errors.Is(err, repository.ErrForbidden):
		writeError(w, http.StatusForbidden, "forbidden", "you do not have permission to read project realtime events")
	case errors.Is(err, repository.ErrNotFound):
		writeError(w, http.StatusNotFound, "not_found", "project was not found")
	case errors.Is(err, repository.ErrInvalidRealtime):
		writeError(w, http.StatusUnprocessableEntity, "validation_error", "realtime request is invalid")
	default:
		writeError(w, http.StatusInternalServerError, "internal_error", "unable to read realtime events")
	}
	return true
}
