/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as ConsoleRouteRouteImport } from './routes/_console/route'
import { Route as AuthAcceptInvitationRouteImport } from './routes/_auth/accept-invitation'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth/forgot-password'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthResetPasswordRouteImport } from './routes/_auth/reset-password'
import { Route as AuthSignupRouteImport } from './routes/_auth/signup'
import { Route as AuthVerifyEmailRouteImport } from './routes/_auth/verify-email'
import { Route as ConsoleIndexRouteImport } from './routes/_console/index'
import { Route as ConsoleSplatRouteImport } from './routes/_console/$'
import { Route as ConsoleAdminIndexRouteImport } from './routes/_console/admin/index'
import { Route as ConsoleAdminSectionRouteImport } from './routes/_console/admin/$section'
import { Route as ConsoleAgentIndexRouteImport } from './routes/_console/agent/index'
import { Route as ConsoleAgentAgentIdRouteImport } from './routes/_console/agent/$agentId'
import { Route as ConsoleProjectsIndexRouteImport } from './routes/_console/projects/index'
import { Route as ConsoleProjectsProjectIdRouteRouteImport } from './routes/_console/projects/$projectId/route'
import { Route as ConsoleProjectsProjectIdIndexRouteImport } from './routes/_console/projects/$projectId/index'
import { Route as ConsoleProjectsProjectIdResourceRouteImport } from './routes/_console/projects/$projectId/$resource'
import { Route as ConsoleProjectsProjectIdApiKeysRouteImport } from './routes/_console/projects/$projectId/api-keys'
import { Route as ConsoleProjectsProjectIdAuthRouteImport } from './routes/_console/projects/$projectId/auth'
import { Route as ConsoleProjectsProjectIdDatabasesRouteImport } from './routes/_console/projects/$projectId/databases'
import { Route as ConsoleProjectsProjectIdDeploymentsRouteImport } from './routes/_console/projects/$projectId/deployments'
import { Route as ConsoleProjectsProjectIdFunctionsRouteImport } from './routes/_console/projects/$projectId/functions'
import { Route as ConsoleProjectsProjectIdLogsRouteImport } from './routes/_console/projects/$projectId/logs'
import { Route as ConsoleProjectsProjectIdMessagingRouteImport } from './routes/_console/projects/$projectId/messaging'
import { Route as ConsoleProjectsProjectIdRealtimeRouteImport } from './routes/_console/projects/$projectId/realtime'
import { Route as ConsoleProjectsProjectIdServicesRouteImport } from './routes/_console/projects/$projectId/services'
import { Route as ConsoleProjectsProjectIdSettingsRouteImport } from './routes/_console/projects/$projectId/settings'
import { Route as ConsoleProjectsProjectIdSitesRouteImport } from './routes/_console/projects/$projectId/sites'
import { Route as ConsoleProjectsProjectIdStorageRouteImport } from './routes/_console/projects/$projectId/storage'
import { Route as ConsoleProjectsProjectIdUsageRouteImport } from './routes/_console/projects/$projectId/usage'
import { Route as ConsoleProjectsProjectIdWebhooksRouteImport } from './routes/_console/projects/$projectId/webhooks'

const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleRouteRoute = ConsoleRouteRouteImport.update({
  id: '/_console',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAcceptInvitationRoute = AuthAcceptInvitationRouteImport.update({
  id: '/accept-invitation',
  path: '/accept-invitation',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthVerifyEmailRoute = AuthVerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => AuthRouteRoute,
} as any)
const ConsoleIndexRoute = ConsoleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ConsoleRouteRoute,
} as any)
const ConsoleSplatRoute = ConsoleSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => ConsoleRouteRoute,
} as any)
const ConsoleAdminIndexRoute = ConsoleAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => ConsoleRouteRoute,
} as any)
const ConsoleAdminSectionRoute = ConsoleAdminSectionRouteImport.update({
  id: '/admin/$section',
  path: '/admin/$section',
  getParentRoute: () => ConsoleRouteRoute,
} as any)
const ConsoleAgentIndexRoute = ConsoleAgentIndexRouteImport.update({
  id: '/agent/',
  path: '/agent/',
  getParentRoute: () => ConsoleRouteRoute,
} as any)
const ConsoleAgentAgentIdRoute = ConsoleAgentAgentIdRouteImport.update({
  id: '/agent/$agentId',
  path: '/agent/$agentId',
  getParentRoute: () => ConsoleRouteRoute,
} as any)
const ConsoleProjectsIndexRoute = ConsoleProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => ConsoleRouteRoute,
} as any)
const ConsoleProjectsProjectIdRouteRoute =
  ConsoleProjectsProjectIdRouteRouteImport.update({
    id: '/projects/$projectId',
    path: '/projects/$projectId',
    getParentRoute: () => ConsoleRouteRoute,
  } as any)
const ConsoleProjectsProjectIdIndexRoute =
  ConsoleProjectsProjectIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ConsoleProjectsProjectIdRouteRoute,
  } as any)
const ConsoleProjectsProjectIdResourceRoute =
  ConsoleProjectsProjectIdResourceRouteImport.update({
    id: '/$resource',
    path: '/$resource',
    getParentRoute: () => ConsoleProjectsProjectIdRouteRoute,
  } as any)
const ConsoleProjectsProjectIdApiKeysRoute =
  ConsoleProjectsProjectIdApiKeysRouteImport.update({
    id: '/api-keys',
    path: '/api-keys',
    getParentRoute: () => ConsoleProjectsProjectIdRouteRoute,
  } as any)
const ConsoleProjectsProjectIdAuthRoute =
  ConsoleProjectsProjectIdAuthRouteImport.update({
    id: '/auth',
    path: '/auth',
    getParentRoute: () => ConsoleProjectsProjectIdRouteRoute,
  } as any)
const ConsoleProjectsProjectIdDatabasesRoute =
  ConsoleProjectsProjectIdDatabasesRouteImport.update({
    id: '/databases',
    path: '/databases',
    getParentRoute: () => ConsoleProjectsProjectIdRouteRoute,
  } as any)
const ConsoleProjectsProjectIdDeploymentsRoute =
  ConsoleProjectsProjectIdDeploymentsRouteImport.update({
    id: '/deployments',
    path: '/deployments',
    getParentRoute: () => ConsoleProjectsProjectIdRouteRoute,
  } as any)
const ConsoleProjectsProjectIdFunctionsRoute =
  ConsoleProjectsProjectIdFunctionsRouteImport.update({
    id: '/functions',
    path: '/functions',
    getParentRoute: () => ConsoleProjectsProjectIdRouteRoute,
  } as any)
const ConsoleProjectsProjectIdLogsRoute =
  ConsoleProjectsProjectIdLogsRouteImport.update({
    id: '/logs',
    path: '/logs',
    getParentRoute: () => ConsoleProjectsProjectIdRouteRoute,
  } as any)
const ConsoleProjectsProjectIdMessagingRoute =
  ConsoleProjectsProjectIdMessagingRouteImport.update({
    id: '/messaging',
    path: '/messaging',
    getParentRoute: () => ConsoleProjectsProjectIdRouteRoute,
  } as any)
const ConsoleProjectsProjectIdRealtimeRoute =
  ConsoleProjectsProjectIdRealtimeRouteImport.update({
    id: '/realtime',
    path: '/realtime',
    getParentRoute: () => ConsoleProjectsProjectIdRouteRoute,
  } as any)
const ConsoleProjectsProjectIdServicesRoute =
  ConsoleProjectsProjectIdServicesRouteImport.update({
    id: '/services',
    path: '/services',
    getParentRoute: () => ConsoleProjectsProjectIdRouteRoute,
  } as any)
const ConsoleProjectsProjectIdSettingsRoute =
  ConsoleProjectsProjectIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => ConsoleProjectsProjectIdRouteRoute,
  } as any)
const ConsoleProjectsProjectIdSitesRoute =
  ConsoleProjectsProjectIdSitesRouteImport.update({
    id: '/sites',
    path: '/sites',
    getParentRoute: () => ConsoleProjectsProjectIdRouteRoute,
  } as any)
const ConsoleProjectsProjectIdStorageRoute =
  ConsoleProjectsProjectIdStorageRouteImport.update({
    id: '/storage',
    path: '/storage',
    getParentRoute: () => ConsoleProjectsProjectIdRouteRoute,
  } as any)
const ConsoleProjectsProjectIdUsageRoute =
  ConsoleProjectsProjectIdUsageRouteImport.update({
    id: '/usage',
    path: '/usage',
    getParentRoute: () => ConsoleProjectsProjectIdRouteRoute,
  } as any)
const ConsoleProjectsProjectIdWebhooksRoute =
  ConsoleProjectsProjectIdWebhooksRouteImport.update({
    id: '/webhooks',
    path: '/webhooks',
    getParentRoute: () => ConsoleProjectsProjectIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof ConsoleIndexRoute
  '/accept-invitation': typeof AuthAcceptInvitationRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/signup': typeof AuthSignupRoute
  '/verify-email': typeof AuthVerifyEmailRoute
  '/$': typeof ConsoleSplatRoute
  '/projects/$projectId': typeof ConsoleProjectsProjectIdRouteRouteWithChildren
  '/admin/$section': typeof ConsoleAdminSectionRoute
  '/agent/$agentId': typeof ConsoleAgentAgentIdRoute
  '/admin/': typeof ConsoleAdminIndexRoute
  '/agent/': typeof ConsoleAgentIndexRoute
  '/projects/': typeof ConsoleProjectsIndexRoute
  '/projects/$projectId/$resource': typeof ConsoleProjectsProjectIdResourceRoute
  '/projects/$projectId/api-keys': typeof ConsoleProjectsProjectIdApiKeysRoute
  '/projects/$projectId/auth': typeof ConsoleProjectsProjectIdAuthRoute
  '/projects/$projectId/databases': typeof ConsoleProjectsProjectIdDatabasesRoute
  '/projects/$projectId/deployments': typeof ConsoleProjectsProjectIdDeploymentsRoute
  '/projects/$projectId/functions': typeof ConsoleProjectsProjectIdFunctionsRoute
  '/projects/$projectId/logs': typeof ConsoleProjectsProjectIdLogsRoute
  '/projects/$projectId/messaging': typeof ConsoleProjectsProjectIdMessagingRoute
  '/projects/$projectId/realtime': typeof ConsoleProjectsProjectIdRealtimeRoute
  '/projects/$projectId/services': typeof ConsoleProjectsProjectIdServicesRoute
  '/projects/$projectId/settings': typeof ConsoleProjectsProjectIdSettingsRoute
  '/projects/$projectId/sites': typeof ConsoleProjectsProjectIdSitesRoute
  '/projects/$projectId/storage': typeof ConsoleProjectsProjectIdStorageRoute
  '/projects/$projectId/usage': typeof ConsoleProjectsProjectIdUsageRoute
  '/projects/$projectId/webhooks': typeof ConsoleProjectsProjectIdWebhooksRoute
  '/projects/$projectId/': typeof ConsoleProjectsProjectIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof ConsoleIndexRoute
  '/accept-invitation': typeof AuthAcceptInvitationRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/signup': typeof AuthSignupRoute
  '/verify-email': typeof AuthVerifyEmailRoute
  '/$': typeof ConsoleSplatRoute
  '/admin/$section': typeof ConsoleAdminSectionRoute
  '/agent/$agentId': typeof ConsoleAgentAgentIdRoute
  '/admin': typeof ConsoleAdminIndexRoute
  '/agent': typeof ConsoleAgentIndexRoute
  '/projects': typeof ConsoleProjectsIndexRoute
  '/projects/$projectId/$resource': typeof ConsoleProjectsProjectIdResourceRoute
  '/projects/$projectId/api-keys': typeof ConsoleProjectsProjectIdApiKeysRoute
  '/projects/$projectId/auth': typeof ConsoleProjectsProjectIdAuthRoute
  '/projects/$projectId/databases': typeof ConsoleProjectsProjectIdDatabasesRoute
  '/projects/$projectId/deployments': typeof ConsoleProjectsProjectIdDeploymentsRoute
  '/projects/$projectId/functions': typeof ConsoleProjectsProjectIdFunctionsRoute
  '/projects/$projectId/logs': typeof ConsoleProjectsProjectIdLogsRoute
  '/projects/$projectId/messaging': typeof ConsoleProjectsProjectIdMessagingRoute
  '/projects/$projectId/realtime': typeof ConsoleProjectsProjectIdRealtimeRoute
  '/projects/$projectId/services': typeof ConsoleProjectsProjectIdServicesRoute
  '/projects/$projectId/settings': typeof ConsoleProjectsProjectIdSettingsRoute
  '/projects/$projectId/sites': typeof ConsoleProjectsProjectIdSitesRoute
  '/projects/$projectId/storage': typeof ConsoleProjectsProjectIdStorageRoute
  '/projects/$projectId/usage': typeof ConsoleProjectsProjectIdUsageRoute
  '/projects/$projectId/webhooks': typeof ConsoleProjectsProjectIdWebhooksRoute
  '/projects/$projectId': typeof ConsoleProjectsProjectIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_console': typeof ConsoleRouteRouteWithChildren
  '/_auth/accept-invitation': typeof AuthAcceptInvitationRoute
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/_auth/verify-email': typeof AuthVerifyEmailRoute
  '/_console/$': typeof ConsoleSplatRoute
  '/_console/': typeof ConsoleIndexRoute
  '/_console/projects/$projectId': typeof ConsoleProjectsProjectIdRouteRouteWithChildren
  '/_console/admin/$section': typeof ConsoleAdminSectionRoute
  '/_console/agent/$agentId': typeof ConsoleAgentAgentIdRoute
  '/_console/admin/': typeof ConsoleAdminIndexRoute
  '/_console/agent/': typeof ConsoleAgentIndexRoute
  '/_console/projects/': typeof ConsoleProjectsIndexRoute
  '/_console/projects/$projectId/$resource': typeof ConsoleProjectsProjectIdResourceRoute
  '/_console/projects/$projectId/api-keys': typeof ConsoleProjectsProjectIdApiKeysRoute
  '/_console/projects/$projectId/auth': typeof ConsoleProjectsProjectIdAuthRoute
  '/_console/projects/$projectId/databases': typeof ConsoleProjectsProjectIdDatabasesRoute
  '/_console/projects/$projectId/deployments': typeof ConsoleProjectsProjectIdDeploymentsRoute
  '/_console/projects/$projectId/functions': typeof ConsoleProjectsProjectIdFunctionsRoute
  '/_console/projects/$projectId/logs': typeof ConsoleProjectsProjectIdLogsRoute
  '/_console/projects/$projectId/messaging': typeof ConsoleProjectsProjectIdMessagingRoute
  '/_console/projects/$projectId/realtime': typeof ConsoleProjectsProjectIdRealtimeRoute
  '/_console/projects/$projectId/services': typeof ConsoleProjectsProjectIdServicesRoute
  '/_console/projects/$projectId/settings': typeof ConsoleProjectsProjectIdSettingsRoute
  '/_console/projects/$projectId/sites': typeof ConsoleProjectsProjectIdSitesRoute
  '/_console/projects/$projectId/storage': typeof ConsoleProjectsProjectIdStorageRoute
  '/_console/projects/$projectId/usage': typeof ConsoleProjectsProjectIdUsageRoute
  '/_console/projects/$projectId/webhooks': typeof ConsoleProjectsProjectIdWebhooksRoute
  '/_console/projects/$projectId/': typeof ConsoleProjectsProjectIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accept-invitation'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/verify-email'
    | '/$'
    | '/projects/$projectId'
    | '/admin/$section'
    | '/agent/$agentId'
    | '/admin/'
    | '/agent/'
    | '/projects/'
    | '/projects/$projectId/$resource'
    | '/projects/$projectId/api-keys'
    | '/projects/$projectId/auth'
    | '/projects/$projectId/databases'
    | '/projects/$projectId/deployments'
    | '/projects/$projectId/functions'
    | '/projects/$projectId/logs'
    | '/projects/$projectId/messaging'
    | '/projects/$projectId/realtime'
    | '/projects/$projectId/services'
    | '/projects/$projectId/settings'
    | '/projects/$projectId/sites'
    | '/projects/$projectId/storage'
    | '/projects/$projectId/usage'
    | '/projects/$projectId/webhooks'
    | '/projects/$projectId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accept-invitation'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/verify-email'
    | '/$'
    | '/admin/$section'
    | '/agent/$agentId'
    | '/admin'
    | '/agent'
    | '/projects'
    | '/projects/$projectId/$resource'
    | '/projects/$projectId/api-keys'
    | '/projects/$projectId/auth'
    | '/projects/$projectId/databases'
    | '/projects/$projectId/deployments'
    | '/projects/$projectId/functions'
    | '/projects/$projectId/logs'
    | '/projects/$projectId/messaging'
    | '/projects/$projectId/realtime'
    | '/projects/$projectId/services'
    | '/projects/$projectId/settings'
    | '/projects/$projectId/sites'
    | '/projects/$projectId/storage'
    | '/projects/$projectId/usage'
    | '/projects/$projectId/webhooks'
    | '/projects/$projectId'
  id:
    | '__root__'
    | '/_auth'
    | '/_console'
    | '/_auth/accept-invitation'
    | '/_auth/forgot-password'
    | '/_auth/login'
    | '/_auth/reset-password'
    | '/_auth/signup'
    | '/_auth/verify-email'
    | '/_console/$'
    | '/_console/'
    | '/_console/projects/$projectId'
    | '/_console/admin/$section'
    | '/_console/agent/$agentId'
    | '/_console/admin/'
    | '/_console/agent/'
    | '/_console/projects/'
    | '/_console/projects/$projectId/$resource'
    | '/_console/projects/$projectId/api-keys'
    | '/_console/projects/$projectId/auth'
    | '/_console/projects/$projectId/databases'
    | '/_console/projects/$projectId/deployments'
    | '/_console/projects/$projectId/functions'
    | '/_console/projects/$projectId/logs'
    | '/_console/projects/$projectId/messaging'
    | '/_console/projects/$projectId/realtime'
    | '/_console/projects/$projectId/services'
    | '/_console/projects/$projectId/settings'
    | '/_console/projects/$projectId/sites'
    | '/_console/projects/$projectId/storage'
    | '/_console/projects/$projectId/usage'
    | '/_console/projects/$projectId/webhooks'
    | '/_console/projects/$projectId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  ConsoleRouteRoute: typeof ConsoleRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_console': {
      id: '/_console'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ConsoleRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/accept-invitation': {
      id: '/_auth/accept-invitation'
      path: '/accept-invitation'
      fullPath: '/accept-invitation'
      preLoaderRoute: typeof AuthAcceptInvitationRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/verify-email': {
      id: '/_auth/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof AuthVerifyEmailRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_console/': {
      id: '/_console/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ConsoleIndexRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/_console/$': {
      id: '/_console/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof ConsoleSplatRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/_console/admin/': {
      id: '/_console/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof ConsoleAdminIndexRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/_console/admin/$section': {
      id: '/_console/admin/$section'
      path: '/admin/$section'
      fullPath: '/admin/$section'
      preLoaderRoute: typeof ConsoleAdminSectionRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/_console/agent/': {
      id: '/_console/agent/'
      path: '/agent'
      fullPath: '/agent/'
      preLoaderRoute: typeof ConsoleAgentIndexRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/_console/agent/$agentId': {
      id: '/_console/agent/$agentId'
      path: '/agent/$agentId'
      fullPath: '/agent/$agentId'
      preLoaderRoute: typeof ConsoleAgentAgentIdRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/_console/projects/': {
      id: '/_console/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ConsoleProjectsIndexRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/_console/projects/$projectId': {
      id: '/_console/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ConsoleProjectsProjectIdRouteRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/_console/projects/$projectId/': {
      id: '/_console/projects/$projectId/'
      path: '/'
      fullPath: '/projects/$projectId/'
      preLoaderRoute: typeof ConsoleProjectsProjectIdIndexRouteImport
      parentRoute: typeof ConsoleProjectsProjectIdRouteRoute
    }
    '/_console/projects/$projectId/$resource': {
      id: '/_console/projects/$projectId/$resource'
      path: '/$resource'
      fullPath: '/projects/$projectId/$resource'
      preLoaderRoute: typeof ConsoleProjectsProjectIdResourceRouteImport
      parentRoute: typeof ConsoleProjectsProjectIdRouteRoute
    }
    '/_console/projects/$projectId/api-keys': {
      id: '/_console/projects/$projectId/api-keys'
      path: '/api-keys'
      fullPath: '/projects/$projectId/api-keys'
      preLoaderRoute: typeof ConsoleProjectsProjectIdApiKeysRouteImport
      parentRoute: typeof ConsoleProjectsProjectIdRouteRoute
    }
    '/_console/projects/$projectId/auth': {
      id: '/_console/projects/$projectId/auth'
      path: '/auth'
      fullPath: '/projects/$projectId/auth'
      preLoaderRoute: typeof ConsoleProjectsProjectIdAuthRouteImport
      parentRoute: typeof ConsoleProjectsProjectIdRouteRoute
    }
    '/_console/projects/$projectId/databases': {
      id: '/_console/projects/$projectId/databases'
      path: '/databases'
      fullPath: '/projects/$projectId/databases'
      preLoaderRoute: typeof ConsoleProjectsProjectIdDatabasesRouteImport
      parentRoute: typeof ConsoleProjectsProjectIdRouteRoute
    }
    '/_console/projects/$projectId/deployments': {
      id: '/_console/projects/$projectId/deployments'
      path: '/deployments'
      fullPath: '/projects/$projectId/deployments'
      preLoaderRoute: typeof ConsoleProjectsProjectIdDeploymentsRouteImport
      parentRoute: typeof ConsoleProjectsProjectIdRouteRoute
    }
    '/_console/projects/$projectId/functions': {
      id: '/_console/projects/$projectId/functions'
      path: '/functions'
      fullPath: '/projects/$projectId/functions'
      preLoaderRoute: typeof ConsoleProjectsProjectIdFunctionsRouteImport
      parentRoute: typeof ConsoleProjectsProjectIdRouteRoute
    }
    '/_console/projects/$projectId/logs': {
      id: '/_console/projects/$projectId/logs'
      path: '/logs'
      fullPath: '/projects/$projectId/logs'
      preLoaderRoute: typeof ConsoleProjectsProjectIdLogsRouteImport
      parentRoute: typeof ConsoleProjectsProjectIdRouteRoute
    }
    '/_console/projects/$projectId/messaging': {
      id: '/_console/projects/$projectId/messaging'
      path: '/messaging'
      fullPath: '/projects/$projectId/messaging'
      preLoaderRoute: typeof ConsoleProjectsProjectIdMessagingRouteImport
      parentRoute: typeof ConsoleProjectsProjectIdRouteRoute
    }
    '/_console/projects/$projectId/realtime': {
      id: '/_console/projects/$projectId/realtime'
      path: '/realtime'
      fullPath: '/projects/$projectId/realtime'
      preLoaderRoute: typeof ConsoleProjectsProjectIdRealtimeRouteImport
      parentRoute: typeof ConsoleProjectsProjectIdRouteRoute
    }
    '/_console/projects/$projectId/services': {
      id: '/_console/projects/$projectId/services'
      path: '/services'
      fullPath: '/projects/$projectId/services'
      preLoaderRoute: typeof ConsoleProjectsProjectIdServicesRouteImport
      parentRoute: typeof ConsoleProjectsProjectIdRouteRoute
    }
    '/_console/projects/$projectId/settings': {
      id: '/_console/projects/$projectId/settings'
      path: '/settings'
      fullPath: '/projects/$projectId/settings'
      preLoaderRoute: typeof ConsoleProjectsProjectIdSettingsRouteImport
      parentRoute: typeof ConsoleProjectsProjectIdRouteRoute
    }
    '/_console/projects/$projectId/sites': {
      id: '/_console/projects/$projectId/sites'
      path: '/sites'
      fullPath: '/projects/$projectId/sites'
      preLoaderRoute: typeof ConsoleProjectsProjectIdSitesRouteImport
      parentRoute: typeof ConsoleProjectsProjectIdRouteRoute
    }
    '/_console/projects/$projectId/storage': {
      id: '/_console/projects/$projectId/storage'
      path: '/storage'
      fullPath: '/projects/$projectId/storage'
      preLoaderRoute: typeof ConsoleProjectsProjectIdStorageRouteImport
      parentRoute: typeof ConsoleProjectsProjectIdRouteRoute
    }
    '/_console/projects/$projectId/usage': {
      id: '/_console/projects/$projectId/usage'
      path: '/usage'
      fullPath: '/projects/$projectId/usage'
      preLoaderRoute: typeof ConsoleProjectsProjectIdUsageRouteImport
      parentRoute: typeof ConsoleProjectsProjectIdRouteRoute
    }
    '/_console/projects/$projectId/webhooks': {
      id: '/_console/projects/$projectId/webhooks'
      path: '/webhooks'
      fullPath: '/projects/$projectId/webhooks'
      preLoaderRoute: typeof ConsoleProjectsProjectIdWebhooksRouteImport
      parentRoute: typeof ConsoleProjectsProjectIdRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthAcceptInvitationRoute: typeof AuthAcceptInvitationRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSignupRoute: typeof AuthSignupRoute
  AuthVerifyEmailRoute: typeof AuthVerifyEmailRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthAcceptInvitationRoute: AuthAcceptInvitationRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSignupRoute: AuthSignupRoute,
  AuthVerifyEmailRoute: AuthVerifyEmailRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface ConsoleProjectsProjectIdRouteRouteChildren {
  ConsoleProjectsProjectIdResourceRoute: typeof ConsoleProjectsProjectIdResourceRoute
  ConsoleProjectsProjectIdApiKeysRoute: typeof ConsoleProjectsProjectIdApiKeysRoute
  ConsoleProjectsProjectIdAuthRoute: typeof ConsoleProjectsProjectIdAuthRoute
  ConsoleProjectsProjectIdDatabasesRoute: typeof ConsoleProjectsProjectIdDatabasesRoute
  ConsoleProjectsProjectIdDeploymentsRoute: typeof ConsoleProjectsProjectIdDeploymentsRoute
  ConsoleProjectsProjectIdFunctionsRoute: typeof ConsoleProjectsProjectIdFunctionsRoute
  ConsoleProjectsProjectIdLogsRoute: typeof ConsoleProjectsProjectIdLogsRoute
  ConsoleProjectsProjectIdMessagingRoute: typeof ConsoleProjectsProjectIdMessagingRoute
  ConsoleProjectsProjectIdRealtimeRoute: typeof ConsoleProjectsProjectIdRealtimeRoute
  ConsoleProjectsProjectIdServicesRoute: typeof ConsoleProjectsProjectIdServicesRoute
  ConsoleProjectsProjectIdSettingsRoute: typeof ConsoleProjectsProjectIdSettingsRoute
  ConsoleProjectsProjectIdSitesRoute: typeof ConsoleProjectsProjectIdSitesRoute
  ConsoleProjectsProjectIdStorageRoute: typeof ConsoleProjectsProjectIdStorageRoute
  ConsoleProjectsProjectIdUsageRoute: typeof ConsoleProjectsProjectIdUsageRoute
  ConsoleProjectsProjectIdWebhooksRoute: typeof ConsoleProjectsProjectIdWebhooksRoute
  ConsoleProjectsProjectIdIndexRoute: typeof ConsoleProjectsProjectIdIndexRoute
}

const ConsoleProjectsProjectIdRouteRouteChildren: ConsoleProjectsProjectIdRouteRouteChildren =
  {
    ConsoleProjectsProjectIdResourceRoute:
      ConsoleProjectsProjectIdResourceRoute,
    ConsoleProjectsProjectIdApiKeysRoute: ConsoleProjectsProjectIdApiKeysRoute,
    ConsoleProjectsProjectIdAuthRoute: ConsoleProjectsProjectIdAuthRoute,
    ConsoleProjectsProjectIdDatabasesRoute:
      ConsoleProjectsProjectIdDatabasesRoute,
    ConsoleProjectsProjectIdDeploymentsRoute:
      ConsoleProjectsProjectIdDeploymentsRoute,
    ConsoleProjectsProjectIdFunctionsRoute:
      ConsoleProjectsProjectIdFunctionsRoute,
    ConsoleProjectsProjectIdLogsRoute: ConsoleProjectsProjectIdLogsRoute,
    ConsoleProjectsProjectIdMessagingRoute:
      ConsoleProjectsProjectIdMessagingRoute,
    ConsoleProjectsProjectIdRealtimeRoute:
      ConsoleProjectsProjectIdRealtimeRoute,
    ConsoleProjectsProjectIdServicesRoute:
      ConsoleProjectsProjectIdServicesRoute,
    ConsoleProjectsProjectIdSettingsRoute:
      ConsoleProjectsProjectIdSettingsRoute,
    ConsoleProjectsProjectIdSitesRoute: ConsoleProjectsProjectIdSitesRoute,
    ConsoleProjectsProjectIdStorageRoute: ConsoleProjectsProjectIdStorageRoute,
    ConsoleProjectsProjectIdUsageRoute: ConsoleProjectsProjectIdUsageRoute,
    ConsoleProjectsProjectIdWebhooksRoute:
      ConsoleProjectsProjectIdWebhooksRoute,
    ConsoleProjectsProjectIdIndexRoute: ConsoleProjectsProjectIdIndexRoute,
  }

const ConsoleProjectsProjectIdRouteRouteWithChildren =
  ConsoleProjectsProjectIdRouteRoute._addFileChildren(
    ConsoleProjectsProjectIdRouteRouteChildren,
  )

interface ConsoleRouteRouteChildren {
  ConsoleSplatRoute: typeof ConsoleSplatRoute
  ConsoleIndexRoute: typeof ConsoleIndexRoute
  ConsoleProjectsProjectIdRouteRoute: typeof ConsoleProjectsProjectIdRouteRouteWithChildren
  ConsoleAdminSectionRoute: typeof ConsoleAdminSectionRoute
  ConsoleAgentAgentIdRoute: typeof ConsoleAgentAgentIdRoute
  ConsoleAdminIndexRoute: typeof ConsoleAdminIndexRoute
  ConsoleAgentIndexRoute: typeof ConsoleAgentIndexRoute
  ConsoleProjectsIndexRoute: typeof ConsoleProjectsIndexRoute
}

const ConsoleRouteRouteChildren: ConsoleRouteRouteChildren = {
  ConsoleSplatRoute: ConsoleSplatRoute,
  ConsoleIndexRoute: ConsoleIndexRoute,
  ConsoleProjectsProjectIdRouteRoute:
    ConsoleProjectsProjectIdRouteRouteWithChildren,
  ConsoleAdminSectionRoute: ConsoleAdminSectionRoute,
  ConsoleAgentAgentIdRoute: ConsoleAgentAgentIdRoute,
  ConsoleAdminIndexRoute: ConsoleAdminIndexRoute,
  ConsoleAgentIndexRoute: ConsoleAgentIndexRoute,
  ConsoleProjectsIndexRoute: ConsoleProjectsIndexRoute,
}

const ConsoleRouteRouteWithChildren = ConsoleRouteRoute._addFileChildren(
  ConsoleRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRouteRoute: AuthRouteRouteWithChildren,
  ConsoleRouteRoute: ConsoleRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
