export type AdminOverviewSnapshot = {
  capturedAt: string | null;
  organizations: number;
  projects: number;
  unavailableProjects: number;
  applicationUsers: number;
  databaseCount: number;
  databaseTableCount: number;
  databaseRowCount: number;
  storageFileCount: number;
  storageBytes: number;
  storageQuotaBytes: number;
  functionCount: number;
  functionArtifactBytes: number;
  functionQuotaBytes: number;
  siteCount: number;
  siteArtifactBytes: number;
  siteReservedBytes: number;
  siteQuotaBytes: number;
  realtimeEventCount: number;
  webhookDeliveryCount7d: number;
};
